# This is a basic workflow to help you get started with Actions

name: Build & Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events to main & 1.3.x branches
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, 1.3.x ]


jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out
    - uses: ouzi-dev/commit-status-updater@v1.1.0
    - uses: actions/setup-java@v2
      name: Set up JDK 8
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - run: mvn -B package --file pom.xml
      name: Build with Maven
    - if: always()
      uses: actions/setup-java@v2
      with:
        status: "${{ job.status }}"
